# Setups ====================================================
# Ubuntu common - dependencies installation
.ubuntu_common: &ubuntuCommon
  before_script:
    - apt-get update -qy
    - apt-get install -y git python3-dev python3-pip

# Ubuntu LTS - latest Ubuntu LTS
.ubuntu_lts: &ubuntuLTS
  image: ubuntu:latest
  <<: *ubuntuCommon

# Ubuntu Rolling - latest Ubuntu (regardless LTS)
.ubuntu_rolling: &ubuntuRolling
  image: ubuntu:rolling
  <<: *ubuntuCommon

# Arch common - dependencies installation
.arch_common: &archCommon
  image: pritunl/archlinux
  before_script:
  - pacman -S --noconfirm python python-pip git base-devel

# Install and run tests
.install_and_run_tests: &installAndRunTests
  script:
  - pip3 install .
  - python3 setup.py test

# Tests ====================================================
# Ubuntu LTS + Python3.5
test:ubuntu_lts_python3.5:
  <<: *ubuntuLTS
  <<: *installAndRunTests

# Ubuntu Rolling + Python3.5
test:ubuntu_rolling_python3.5:
  <<: *ubuntuRolling
  <<: *installAndRunTests

test:arch_python3.6:
  <<: *archCommon
  <<: *installAndRunTests
